### ISSUE TITLE
Unrecognised card type 3001

### ISSUE THREAD

**Issue by robtaylor** [mbrobbel/capi-flash-script#4]
Hi we have a CAPI card identifying as 3001 (Alphadata KU3). Is it possible to update to support this?

**Comment by mbrobbel** [comment]
Hi Rob, 
I've added the PSL revision so that the script can recognize those cards.
I don't have access to the corresponding binary, but if you are allowed to share it, please feel free to open a pull request.
Also, please refer to #2 and #3, and consider contacting Frank and Ken for further support.

**Comment by mbrobbel** [comment]
Please check the fork of @kenhill
https://github.com/kenhill/capi-flash-script

This repository has binaries for other PSL revisions.
